SELECT * FROM Sailors;
SELECT * FROM Sailors A, Sailors B WHERE A.A = B.A ORDER BY A.B;
SELECT * FROM Sailors, Boats WHERE Sailors.B = Boats.F AND Sailors.A > 9000 AND Boats.E < 1000 AND Boats.D != 1200 ORDER BY Sailors.C;
SELECT * FROM Sailors WHERE Sailors.B < 2500 ORDER BY Sailors.B;
SELECT DISTINCT Boats.E FROM Sailors, Boats WHERE Boats.F <= 200 AND Boats.E <= Sailors.B ORDER BY Sailors.C;
SELECT DISTINCT * FROM Sailors S ORDER BY S.B;

SELECT DISTINCT S1.A, S2.A, B.D
FROM Sailors S1, Sailors S2, Boats B
WHERE B.F >= 3000 AND B.F < 5000 AND S1.A = B.D AND S1.A < 2000
ORDER BY B.D, S2.A;

SELECT DISTINCT B1.D, B2.D
FROM Boats B1, Boats B2
WHERE B1.E < B2.E AND B1.E < 2000
ORDER BY B2.F;
